-- Rode conectado no XEPDB1 como ESG (ou com CURRENT_SCHEMA=ESG)
ALTER SESSION SET CURRENT_SCHEMA=ESG;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_RANKING_SUSTENTABILIDADE';
EXCEPTION WHEN OTHERS THEN NULL; END;


BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ALERTA_CONSUMO_ANORMAL';
EXCEPTION WHEN OTHERS THEN NULL; END;


BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CALCULAR_ECONOMIA_CO2';
EXCEPTION WHEN OTHERS THEN NULL; END;


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE GERACAO_SOLAR CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CONSUMO_ENERGIA CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EQUIPAMENTOS CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PAINEIS_SOLARES CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SETORES CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL; END;

COMMIT;
